stages:
    - development
    - install
    - deploy

.check the development:
    image: node
    stage: development
    script:
    - npm ci

.check the install using using yarn:
    image: node
    stage: install
    script:
        - yarn cache clean
        - yarn add universal-cookie
        - yarn install
        - yarn build
    artifacts:
        paths:
            - build

deploy_to_s3:
    stage: deploy
    image:
        name: amazon/aws-cli:2.13.1
        entrypoint: [""]
    script:
        - aws --version
        - echo "Hello s3" > test.txt
        - aws s3 cp test.txt s3://$AWS_S3_BUCKET/test.txt



